package TwentyHoles::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

=head1 NAME

TwentyHoles::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<TwentyHoles>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<TwentyHoles::DB>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.54

=head1 AUTHOR

Carl Johstone

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
